### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'nancumprod'

### ISSUE THREAD

**Issue by ZeliangSu** [nikitinvv/lprec#5]
I'm repporting this error that I couldn't solve
**Python**: 3.6
**Installation**: from conda
**numpy version**:1.11.3
**tomopy version**: 1.5.2
/home/tomoserver/anaconda3/envs/tomo/bin/python /media/tomoserver/DATA/zeliang/working_directory/script/recon_lprec.py
Traceback (most recent call last):
  File "/recon_lprec.py", line 2, in <module>
    import tomopy
  File "/anaconda3/envs/tomo/lib/python3.6/site-packages/tomopy/__init__.py", line 65, in <module>
    from tomopy.misc.phantom import *
  File "/anaconda3/envs/tomo/lib/python3.6/site-packages/tomopy/misc/phantom.py", line 57, in <module>
    import skimage
  File "/anaconda3/envs/tomo/lib/python3.6/site-packages/skimage/__init__.py", line 167, in <module>
    from .util.dtype import (img_as_float32,
  File "/anaconda3/envs/tomo/lib/python3.6/site-packages/skimage/util/__init__.py", line 6, in <module>
    from .apply_parallel import apply_parallel
  File "/anaconda3/envs/tomo/lib/python3.6/site-packages/skimage/util/apply_parallel.py", line 8, in <module>
    import dask.array as da
  File "/anaconda3/envs/tomo/lib/python3.6/site-packages/dask/array/__init__.py", line 5, in <module>
    from .core import (
  File "/anaconda3/envs/tomo/lib/python3.6/site-packages/dask/array/core.py", line 29, in <module>
    from . import chunk
  File "/anaconda3/envs/tomo/lib/python3.6/site-packages/dask/array/chunk.py", line 70, in <module>
    nancumprod = np.nancumprod
AttributeError: module 'numpy' has no attribute 'nancumprod'

I use the lprec in the following way:
```
rec = tomopy.recon(
     prj, theta, 
     center=bcenter/pow(2, binning),
     algorithm=tomopy.lprec, lpmethod='tv', 
     filter_name='parzen', 
     ncore=1
)
```

**Comment by ZeliangSu** [comment]
There's a conflict between astra's and lprec's library. It seems that one shouldn't install astra-toolbox after lprec which will downgrade numpy and make a mess. I simply solved it by creating new env for lprec and another one for astra.
